## 01-openvpn.yaml
## ansible-playbook 01-openvpn.yaml -i inventory/hosts.ini
---
- name: OpenVpn
  hosts: pvr
  gather_facts: no
  become: yes
  roles:
    - role: openvpn

## Check IP: curl https://ipinfo.io/ip
## Check Torrent IP: https://torguard.net/checkmytorrentipaddress.php