## 01-transmission.yaml
## ansible-playbook 01-transmission.yaml -i inventory/hosts.ini
---
- name: Transmission
  hosts: pvr
  gather_facts: no
  become: yes
  roles:
    - role: transmission

## Check Torrent IP: https://torguard.net/checkmytorrentipaddress.php