- name: "Create directory {{ USB_MOUNT_POINT }} to mount usb stick"
  file:
    path: "{{ USB_MOUNT_POINT }}"
    state: directory

- name: Get the UUID of usb stick
  delegate_facts: true
  shell: | 
    blkid /dev/sda1 | awk -F'"' '{print $2}'
  register: uuid

- name: Mount USB stick by UUID
  ansible.posix.mount:
    src: "UUID={{ uuid.stdout }}"
    path: "{{ USB_MOUNT_POINT }}"
    fstype: vfat
    opts: rw,defaults,umask=000
    dump: 0
    passno: 2
    state: mounted

- name: Create pvr directory on USB stick
  file:
    path: "{{ USB_MOUNT_POINT }}/pvr"
    state: directory

- name: "Symbolic link /home/{{ PVR_USERNAME }}/.config to {{ USB_MOUNT_POINT }}/pvr"
  file:
    src: "{{ USB_MOUNT_POINT }}/pvr"
    dest: "/home/{{ PVR_USERNAME }}/.config"
    # owner: "{{ PVR_UID }}"
    # group: "{{ PVR_GID }}"
    state: link
