- name: "Create {{ PVR_USERNAME }} with UID {{ PVR_UID }} and GID {{ PVR_GID }}"
  ansible.builtin.user:
    name: "{{ PVR_USERNAME }}"
    password: "{{ PVR_PASSWORD | password_hash('sha512') }}"
    update_password: on_create
    shell: /bin/zsh
    uid: "{{ PVR_UID }}"
    group: "{{ PVR_GID }}"
    append: yes
    groups:
      - nogroup

- name: Install nfs-common
  ansible.builtin.apt: 
    name: ['nfs-common']
    state: latest
    autoclean: yes
    autoremove: yes

- name: Create mount path
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: 0777
  with_items: "{{ MOUNT_PATHS }}"

- name: Mount network share
  ansible.posix.mount:
    src: "{{ NAS_NAME }}:{{ item.src }}"
    path: "{{ item.path }}"
    fstype: nfs
    opts: defaults
    dump: 0
    passno: 2
    state: mounted
  with_items: "{{ NFS_MOUNTS }}"

- name: Last steps to apply file ownership and cleanup
  command: df -kh