- name: Install Transmission package
  ansible.builtin.apt: 
    name: "{{ item }}"
    state: latest
    autoclean: yes
    autoremove: yes
  with_items:
    - transmission-daemon

- name: Make sure transmission daemon is not running before modifying config
  service:
    name: transmission-daemon
    state: stopped
  ignore_errors: true

- name: Allow Transmission Web
  community.general.ufw:
    rule: allow
    port: '{{ RPC_PORT }}'
    proto: tcp
    comment: Allow Transmission Web
  notify: ufw reload

- name: Allow Transmission peer port
  community.general.ufw:
    rule: allow
    port: '{{ PEER_PORT }}'
    proto: tcp
    comment: Allow Transmission peer port
  notify: ufw reload

- name: Create a supplement file directory for transmission
  ansible.builtin.file:
    path: /etc/systemd/system/transmission-daemon.service.d
    state: directory

- name: Copy run-as-user.conf supplement file into directory
  template:
    src: run-as-user.conf.j2
    dest: /etc/systemd/system/transmission-daemon.service.d/run-as-user.conf

- name: Tell systemd to reload units.
  shell: |
    sudo systemctl daemon-reload

- name: "Set setuid {{ PVR_UID }} in /etc/init.d/transmission-daemon"
  ansible.builtin.lineinfile:
    path: /etc/init.d/transmission-daemon
    state: present
    regexp: '^USER='
    line: 'USER= {{ PVR_UID }}'

# - name: "Set setuid {{ PVR_UID }} in /etc/init/transmission-daemon.conf"
#   ansible.builtin.lineinfile:
#     path: '/etc/init/transmission-daemon.conf'
#     state: present
#     regexp: '^setuid'
#     line: 'setuid {{ PVR_UID }}'

# - name: "Set setgid {{ PVR_GID }} in /etc/init/transmission-daemon.conf"
#   ansible.builtin.lineinfile:
#     path: '/etc/init/transmission-daemon.conf'
#     state: present
#     regexp: '^setgid'
#     line: 'setgid {{ PVR_GID }}'

- name: "Copy Transmission init to /etc/init/transmission-daemon.conf"
  template:
    src: transmission-daemon.conf.j2
    dest: /etc/init/transmission-daemon.conf

- name: Create transmission-daemon config folder
  ansible.builtin.file:
    path: "/home/{{ PVR_USERNAME }}/.config/transmission-daemon"
    state: directory

- name: "Copy Transmission configuration to /home/{{ PVR_USERNAME }}/.config/transmission-daemon/settings.json"
  template:
    src: settings.json.j2
    dest: /home/{{ PVR_USERNAME }}/.config/transmission-daemon/settings.json

- name: Add users to transmission group
  user:
    name: "{{ item }}"
    groups: debian-transmission
    append: yes
  with_items: 
    - "{{ DEFAULT_USER }}"
    - "{{ PVR_USERNAME }}"

- name: "Add debian-transmission to {{ PVR_GID }}"
  user:
    name: debian-transmission
    groups: " {{ PVR_GID }}" 
    append: yes

- name: Start transmission daemon now config written
  systemd:
    name: transmission-daemon
    state: started

- name: Restart systemd daemons
  shell: |
    systemctl daemon-reload

## https://unix.stackexchange.com/questions/624899/transmission-daemon-running-under-custom-user-trying-to-load-config-from-wrong-p
## https://www.golinuxcloud.com/run-systemd-service-specific-user-group-linux/