- name: Install Prowlarr dependencies
  ansible.builtin.apt: 
    name: "{{ item }}"
    state: latest
    autoclean: yes
    autoremove: yes
    update_cache: yes
  with_items:
    - curl
    - sqlite3

- name: Add Mono apt key from keyserver.ubuntu.com
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

- name: Add Mono repository
  ansible.builtin.apt_repository:
    repo: deb https://download.mono-project.com/repo/ubuntu stable-focal main
    state: present

- name: Install mono-devel package
  ansible.builtin.apt: 
    name: mono-devel
    state: latest
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: Create /opt/prowlarr directory
  ansible.builtin.file:
    path: /opt/prowlarr
    state: directory
    owner: "{{ PVR_UID }}"
    group: "{{ PVR_GID }}"

- name: Download and unzip Prowlarr to /opt/prowlarr
  ansible.builtin.unarchive:
    src: "http://prowlarr.servarr.com/v1/update/develop/updatefile?os=linux&runtime=netcore&arch=arm64"
    dest: /opt/prowlarr
    owner: "{{ PVR_UID }}"
    group: "{{ PVR_GID }}"
    remote_src: yes
    extra_opts:
      - --strip-components=1

- name: Update file permissions
  ansible.builtin.file:
    path: /opt/prowlarr
    owner: "{{ PVR_UID }}"
    group: "{{ PVR_GID }}"
    recurse: yes

- name: "Create Prowlarr working directory /home/{{ PVR_USERNAME }}/.config/prowlarr"
  ansible.builtin.file:
    path: "/home/{{ PVR_USERNAME }}/.config/prowlarr"
    state: directory

- name: Make sure Prowlarr daemon is not running before modifying
  ansible.builtin.systemd:
    name: prowlarr.service
    state: stopped
  ignore_errors: true

- name: Copy Prowlarr daemon service file
  ansible.builtin.template:
    src: prowlarr.service.j2
    dest: /etc/systemd/system/prowlarr.service
    mode: 0644

- name: Reload systemd
  ansible.builtin.command: |
    systemctl -q daemon-reload

- name: Start Prowlarr service
  ansible.builtin.systemd:
    name: prowlarr.service
    enabled: yes
    daemon_reload: yes
    state: reloaded