- name: Allow ansible user to execute without password
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^{{ ansible_user }}" # RegEx to check for state present
    line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"

- name: Remove ansible account password login
  ansible.builtin.command: "passwd -d {{ ansible_user }}"